tz: "Asia/Kolkata"
out_dir: "reports"

zerodha_enabled: true
ZERODHA_API_KEY: ""
ZERODHA_API_SECRET: ""
ZERODHA_ACCESS_TOKEN: ""
TELEGRAM_BOT_TOKEN: ""
TELEGRAM_CHAT_ID: ""

capital_rs: 100000
order_qty: 1

# --- GLOBAL (prepare_signals reads these too) ---
ema_fast: 21
ema_slow: 50
rsi_len: 14
rsi_buy: 50
rsi_sell: 50
ema_poke_pct: 0.0001   # 0.01%
atr_len: 14

stop_atr_mult: 1.0
take_atr_mult: 1.2
trailing_enabled: true
trail_start_atr: 0.5
trail_atr_mult: 1.0

reentry_max: 12
reentry_cooldown: 0

intraday_options:
  underlying: "BANKNIFTY"
  index_token: 260105
  timeframe: "5minute"
  strike_step: 100
  ma_len: 20
  atr_len: 14
  sl_atr_mult: 1.0
  tgt_rr: 1.2
  trail_start_atr: 0.5
  trail_atr_mult: 1.0
  reentry_max: 12
  reentry_cooldown: 0

send_only_signals: true
paper_trading: true
live_trading: false

# --- BACKTEST block mirrors (so either path works) ---
backtest:
  session_start: "09:20"
  session_end:   "15:20"

  slippage_bps: 2.0
  brokerage_flat: 20.0
  brokerage_pct: 0.0003

  ema_fast: 21
  ema_slow: 50
  rsi_len: 14
  rsi_buy: 50
  rsi_sell: 50
  atr_len: 14
  ema_poke_pct: 0.0001

  reentry:
    max_per_day: 20
    cooldown_bars: 0

  guardrails:
    max_trades_per_day: 30
    max_daily_loss_rs: 2500
    stop_after_target_rs: 4000

  exits:
    stop_atr_mult: 1.0
    take_atr_mult: 1.2
    trail:
      type: "atr"
      atr_mult: 1.0
      step_bars: 3
