tz: "Asia/Kolkata"
out_dir: "reports"

zerodha_enabled: true
ZERODHA_API_KEY: ""
ZERODHA_API_SECRET: ""
ZERODHA_ACCESS_TOKEN: ""
TELEGRAM_BOT_TOKEN: ""
TELEGRAM_CHAT_ID: ""

capital_rs: 100000
order_qty: 1

# ---- Global params (legacy; safe to keep) ----
ema_fast: 21
ema_slow: 50
rsi_len: 14
rsi_buy: 52
rsi_sell: 48
atr_len: 14
ema_poke_pct: 0.0001

stop_atr_mult: 1.0
take_atr_mult: 1.3
trailing_enabled: true
trail_start_atr: 0.5
trail_atr_mult: 1.0

reentry_max: 12
reentry_cooldown: 0

intraday_options:
  underlying: "BANKNIFTY"
  index_token: 260105
  timeframe: "5minute"
  strike_step: 100
  ma_len: 20
  atr_len: 14
  sl_atr_mult: 1.0
  tgt_rr: 1.3
  trail_start_atr: 0.5
  trail_atr_mult: 1.0
  reentry_max: 12
  reentry_cooldown: 0

send_only_signals: true
paper_trading: true
live_trading: false

# ---- Backtest defaults ----
backtest:
  session_start: "09:20"
  session_end:   "15:20"
  strategy: intraday_rsi

  # Execution / costs
  slippage_bps: 2.0
  brokerage_flat: 20.0
  brokerage_pct: 0.0003

  # Indicators
  rsi_len: 14
  rsi_overbought: 70
  rsi_oversold: 30
  ema_fast: 21
  ema_slow: 50
  trend_filter: true
  htf_minutes: 5
  atr_len: 14

  # Risk / exits
  atr_mult_sl: 1.9
  atr_mult_tp: 2.6
  risk_perc: 0.002
  order_qty: 1
  capital_rs: 100000
  allow_shorts: false

  # Behaviour
  min_hold_bars: 5
  cooldown_bars: 4
  trail_after_hold: true

  # Entries only during these windows (HH:MM-HH:MM)
  entry_windows: ["09:20-10:00", "14:30-15:15"]

# ---- Profile overrides ----
backtest_loose:
  atr_mult_sl: 1.8
  atr_mult_tp: 2.5
  entry_windows: ["09:20-10:15", "14:15-15:10"]

backtest_medium:
  atr_mult_sl: 2.0
  atr_mult_tp: 2.6
  min_hold_bars: 6
  cooldown_bars: 5
  entry_windows: ["09:20-10:00", "14:30-15:15"]

backtest_strict:
  atr_mult_sl: 2.1
  atr_mult_tp: 2.7
  min_hold_bars: 6
  cooldown_bars: 6
  rsi_overbought: 72
  rsi_oversold: 28
  entry_windows: ["09:20-09:55", "14:35-15:10"]
