# =========================
# Quant Bot — Base Config
# =========================

# ---- Data / timeframe ----
symbol: "NIFTYBEES.NS"
interval: "1d"
lookback: "1y"
tz: "Asia/Kolkata"

# ---- Zerodha switch ----
zerodha_enabled: true
zerodha_instrument_token: null   # fill if you have it; otherwise Zerodha still works via symbol mapping inside code

# ---- Strategy params ----
ema_fast: 21
ema_slow: 50
rsi_len: 14
rsi_buy: 30
rsi_sell: 70
adx_len: 14
atr_len: 14

# ---- Risk / sizing ----
stop_atr_mult: 2.0
take_atr_mult: 3.0
capital_rs: 100000
order_qty: 1

# ---- Modes ----
send_only_signals: true
paper_trading: true
live_trading: false

# ---- Output ----
out_dir: "reports"

# ---- Simulation control ----
# If true, runner will ONLY use candles up to “yesterday” (India time).
simulate_yesterday_only: true
# Optional alternative: instead of yesterday, you can hard-set a date.
# paper_trade_cutoff: "2025-08-21"   # YYYY-MM-DD  (leave commented for “yesterday”)

# ---- Telegram (secrets normally set in Actions) ----
telegram_bot_token: ""
telegram_chat_id: ""

# ---- Zerodha creds (secrets normally set in Actions) ----
zerodha_api_key: ""
zerodha_api_secret: ""
zerodha_access_token: ""
