# =========================
# Quant Bot — Base Config
# =========================

# ---- General / timezone ----
tz: "Asia/Kolkata"

# ---- Zerodha only ----
zerodha_enabled: true
# Your ACCESS TOKEN is read from env (GitHub Secrets), not from this file.

# ---- Daily swing runner (unchanged; still available) ----
symbol: "^NSEI"
interval: "1d"
lookback: "1y"

# ---- Capital & risk (generic) ----
capital_rs: 100000
order_qty: 1

# ---- Modes ----
send_only_signals: true
paper_trading: true
live_trading: false

# ---- Output ----
out_dir: "reports"

# =========================
# Intraday Options (NEW)
# =========================
intraday_options:
  # Underlying & lot settings
  underlying: "BANKNIFTY"        # "NIFTY" or "BANKNIFTY"
  lots: 1                         # paper lots
  lot_size: 15                    # BANKNIFTY = 15, NIFTY = 50 (update if needed)

  # Timing (IST)
  entry_time:  "09:30"            # first bar to take entry after market open
  squareoff:   "15:10"            # auto exit time
  date: ""                        # "" = today; or "YYYY-MM-DD" to simulate a past day

  # OHLC interval for options
  interval: "5minute"

  # Strategy: ATM Short Straddle (SELL CE & SELL PE at entry time)
  entry_rule: "atm_short_straddle"

  # Risk management (per leg)
  leg_sl_percent: 30.0            # 30% SL of entry premium per leg
  combined_target_percent: 50.0   # optional: book when combined premium drops 50%
  trail: false

  # ---- Re-entry & Trailing ----
reentry_max: 2           # allow up to 2 re-entries after an exit (per day)
reentry_cooldown: 2      # bars to wait after exit before re-entering
trailing_enabled: true   # turn trailing on/off
trail_type: "atr"        # "atr" (supported)
trail_start_atr: 1.0     # start trailing once unrealized > 1.0 * ATR
trail_atr_mult: 1.5      # trail distance = 1.5 * ATR
adx_min: 10              # require minimum trend strength for entries

  # Telegram (optional; read from secrets if running in Actions)
  telegram_bot_token: ""
  telegram_chat_id: ""
