# =========================
# Quant Bot — Zerodha Only
# =========================

# ---- Data / timeframe ----
symbol: "^NSEI"            # not used for Zerodha fetch, kept for logs
interval: "1d"             # '1d','1h','15m','5m'
lookback: "1y"
tz: "Asia/Kolkata"

# ---- Zerodha ONLY ----
zerodha_enabled: true
# NIFTY index instrument token (Spot index candles via Zerodha historical API)
# Use your chosen token here. Example below for NIFTY 50 spot:
zerodha_instrument_token: 256265

# ---- Strategy params ----
ema_fast: 21
ema_slow: 50
rsi_len: 14
rsi_buy: 30
rsi_sell: 70
adx_len: 14
atr_len: 14

# ---- Risk / sizing (paper only today) ----
stop_atr_mult: 2.0
take_atr_mult: 3.0
capital_rs: 100000
order_qty: 1

# ---- Modes ----
send_only_signals: true     # send alerts only
paper_trading: true         # <-- stays paper for today
live_trading: false

# ---- Output ----
out_dir: "reports"

# ---- (future) live defaults ----
trade:
  exchange: "NSE"
  product: "CNC"
  order_type: "MARKET"
  qty: 1

# ---- Telegram (populated by GitHub Secrets at runtime) ----
telegram_bot_token: ""
telegram_chat_id: ""

# ---- Zerodha creds (populated by GitHub Secrets at runtime) ----
zerodha_api_key: ""
zerodha_api_secret: ""
zerodha_access_token: ""
