tz: "Asia/Kolkata"
out_dir: "reports"

zerodha_enabled: true
ZERODHA_API_KEY: ""
ZERODHA_API_SECRET: ""
ZERODHA_ACCESS_TOKEN: ""
TELEGRAM_BOT_TOKEN: ""
TELEGRAM_CHAT_ID: ""

capital_rs: 100000
order_qty: 1

# ---- Global params ----
ema_fast: 21
ema_slow: 50
rsi_len: 14
rsi_buy: 52
rsi_sell: 48
atr_len: 14
ema_poke_pct: 0.0001

stop_atr_mult: 1.0
take_atr_mult: 1.3
trailing_enabled: true
trail_start_atr: 0.5
trail_atr_mult: 1.0

reentry_max: 12
reentry_cooldown: 0

intraday_options:
  underlying: "BANKNIFTY"
  index_token: 260105
  timeframe: "5minute"
  strike_step: 100
  ma_len: 20
  atr_len: 14
  sl_atr_mult: 1.0
  tgt_rr: 1.3
  trail_start_atr: 0.5
  trail_atr_mult: 1.0
  reentry_max: 12
  reentry_cooldown: 0

send_only_signals: true
paper_trading: true
live_trading: false

# ---- Backtest block ----
backtest:
  session_start: "09:20"
  session_end:   "15:20"

  slippage_bps: 2.0
  brokerage_flat: 20.0
  brokerage_pct: 0.0003

  # === STRATEGY SWITCH ===
  strategy: intraday_rsi        # or: ema_rsi_adx

  # --- RSI params ---
  rsi_len: 14
  rsi_overbought: 70
  rsi_oversold: 30

  # --- EMA (for HTF filter) ---
  ema_fast: 21
  ema_slow: 50

  # --- ATR / SL-TP ---
  atr_len: 14
  atr_mult_sl: 1.8
  atr_mult_tp: 2.5

  # --- Risk & Capital ---
  risk_perc: 0.002
  order_qty: 1
  capital_rs: 100000

  # --- Behaviour controls ---
  allow_shorts: false
  trend_filter: true
  htf_minutes: 5

  min_hold_bars: 5
  cooldown_bars: 3
  trail_after_hold: true

# ---- Profile overrides ----
backtest_loose:
  atr_mult_sl: 1.8
  atr_mult_tp: 2.6

backtest_medium:
  atr_mult_sl: 1.9
  atr_mult_tp: 2.4

backtest_strict:
  atr_mult_sl: 2.0
  atr_mult_tp: 2.3
  min_hold_bars: 6
