# =========================
# Quant Bot — Base Config
# =========================

# ---- Data / timeframe (daily swing engine; unchanged) ----
symbol: "^NSEI"
interval: "1d"
lookback: "1y"
tz: "Asia/Kolkata"

# ---- Zerodha switch (used by both daily & intraday) ----
zerodha_enabled: true
zerodha_instrument_token: 256265   # NIFTYBEES token; not used by intraday options
                                   # but keep it for your daily runner

# ---- Strategy params (daily swing; unchanged) ----
ema_fast: 21
ema_slow: 50
rsi_len: 14
rsi_buy: 30
rsi_sell: 70
adx_len: 14
atr_len: 14

# ---- Risk / sizing (daily) ----
stop_atr_mult: 2.0
take_atr_mult: 3.0
capital_rs: 100000
order_qty: 1

# ---- Modes (daily) ----
send_only_signals: true
paper_trading: true
live_trading: false

# ---- Output ----
out_dir: "reports"

# ---- Simulation control (daily) ----
simulate_yesterday_only: false
research_lookback: "2y"

# ---- Telegram (usually via GitHub Secrets) ----
telegram_bot_token: ""
telegram_chat_id: ""

# ---- Zerodha creds (usually via GitHub Secrets) ----
zerodha_api_key: ""
zerodha_api_secret: ""
zerodha_access_token: ""

# ---- Intraday Options (BANKNIFTY, paper-only) ----
options_intraday:
  enabled: true
  underlying: "BANKNIFTY"     # first target
  strike_step: 100            # BANKNIFTY strikes spacing
  interval: "5m"              # 5-minute candles
  ema_fast: 9
  ema_slow: 21
  entry_start: "09:25"        # first allowed entry (IST)
  entry_end:   "14:45"        # last new entry (IST)
  hard_exit:   "15:20"        # force square-off (IST)
  sl_pct: 25                  # stop-loss percent
  target_pct: 40              # take-profit percent
  qty: 1                      # lots; PAPER ONLY in this runner
  paper_trading: true
  live_trading: false
