tz: "Asia/Kolkata"
out_dir: "reports"

zerodha_enabled: true
ZERODHA_API_KEY: ""
ZERODHA_API_SECRET: ""
ZERODHA_ACCESS_TOKEN: ""
TELEGRAM_BOT_TOKEN: ""
TELEGRAM_CHAT_ID: ""

capital_rs: 100000
order_qty: 1

# ---- Global params (prepare_signals પણ વાંચે છે) ----
ema_fast: 21
ema_slow: 50
rsi_len: 14
rsi_buy: 52
rsi_sell: 48
atr_len: 14
ema_poke_pct: 0.0001

# exits (global mirrors)
stop_atr_mult: 1.0
take_atr_mult: 1.3
trailing_enabled: true
trail_start_atr: 0.5
trail_atr_mult: 1.0

# Re-entries (used by backtest guardrails as well)
reentry_max: 12
reentry_cooldown: 0

intraday_options:
  underlying: "BANKNIFTY"
  index_token: 260105
  timeframe: "5minute"
  strike_step: 100
  ma_len: 20
  atr_len: 14
  sl_atr_mult: 1.0
  tgt_rr: 1.3
  trail_start_atr: 0.5
  trail_atr_mult: 1.0
  reentry_max: 12
  reentry_cooldown: 0

send_only_signals: true
paper_trading: true
live_trading: false

# ---- Backtest block (engine primary) ----
backtest:
  session_start: "09:20"
  session_end:   "15:20"

  slippage_bps: 2.0
  brokerage_flat: 20.0
  brokerage_pct: 0.0003

  # Strategy mirrors
  ema_fast: 21
  ema_slow: 50
  rsi_len: 14
  rsi_buy: 52
  rsi_sell: 48
  atr_len: 14
  ema_poke_pct: 0.0001

  # NEW quality filters
  filters:
    adx_len: 14
    adx_min: 15           # trend-strength
    use_htf: true
    htf_rule: "15min"     # higher timeframe for confirmation
    htf_ema_len: 20
    min_atr_pct: 0.0003   # avoid dead periods
    session_start: "09:25"
    session_end:   "15:15"

  reentry:
    max_per_day: 20
    cooldown_bars: 0

  guardrails:
    max_trades_per_day: 30
    max_daily_loss_rs: 2500
    stop_after_target_rs: 4000

  exits:
    stop_atr_mult: 1.0
    take_atr_mult: 1.3
    trail:
      type: "atr"
      atr_mult: 1.0
      step_bars: 3
