# Core configuration (safe to edit)
symbol: "RELIANCE.BO"    # change from ^NSEI to any valid NSE stock
interval: "1d"
lookback: "1y"
tz: "Asia/Kolkata"

# Strategy
ema_fast: 21
ema_slow: 50
rsi_len: 14
rsi_buy: 30
rsi_sell: 70
adx_len: 14
atr_len: 14

# Risk / position sizing
stop_atr_mult: 2.0
take_atr_mult: 3.0
capital_rs: 100000
order_qty: 1

# Modes
send_only_signals: true
paper_trading: true
live_trading: false

# Output dir (reports are committed here)
out_dir: "reports"
