# =========================
# Quant Bot — Zerodha-only
# =========================

# ---- Data / timeframe ----
symbol: "NIFTYBEES.NS"      # not used for Yahoo, kept only for log clarity
interval: "1d"
lookback: "1y"
tz: "Asia/Kolkata"

# ---- Zerodha ----
zerodha_enabled: true
zerodha_instrument_token: 256265   # NIFTY 50 index

# ---- Strategy params ----
ema_fast: 21
ema_slow: 50
rsi_len: 14
rsi_buy: 30
rsi_sell: 70
adx_len: 14
atr_len: 14

# ---- Risk / sizing ----
capital_rs: 10000
order_qty: 1
stop_atr_mult: 2.0
take_atr_mult: 3.0

# ---- Modes ----
send_only_signals: true
paper_trading: true     # ✅ default tomorrow = paper
live_trading: false

# ---- Output ----
out_dir: "reports"

# ---- Optional: Telegram (normally via GitHub Secrets) ----
telegram_bot_token: ""
telegram_chat_id: ""

# ---- Optional: Zerodha creds (normally via GitHub Secrets) ----
zerodha_api_key: ""
zerodha_api_secret: ""
zerodha_access_token: ""

# ---- Trading defaults (future live mode) ----
trade:
  exchange: "NSE"
  product: "CNC"
  order_type: "MARKET"
  qty: 1
