# =========================
# Intraday Options — Pure Repo Config
# =========================
tz: "Asia/Kolkata"

# ---- Zerodha (env overrides via GitHub Actions secrets) ----
zerodha_enabled: true
zerodha_api_key: ""
zerodha_api_secret: ""
zerodha_access_token: ""

# ---- Mode toggle ----
# "index"  -> fast prototyping on underlying
# "options"-> realistic CE/PE leg simulation
mode: "options"

# ---- Underlying / session ----
underlying: "BANKNIFTY"      # or "NIFTY"
index_token: 260105          # BANKNIFTY; NIFTY = 256265
timeframe: "5minute"
strike_step: 100
session:
  start: "09:20"             # IST
  end:   "15:15"

# ---- Capital & sizing ----
capital_rs: 100000
order_qty: 1                 # lots or contracts-per-trade (used consistently)

# ---- Entry / Exit (shared semantics) ----
entry:
  ema_fast: 21
  ema_slow: 50
  rsi_len: 14
  rsi_buy: 30
  rsi_sell: 70
  adx_len: 14
  atr_len: 14
  adx_min: 10

risk:
  stop_atr_mult: 1.0         # per leg (options) or per bar ATR (index)
  take_rr: 1.5               # target = take_rr * risk-per-trade

trailing:
  enabled: true
  type: "atr"
  trail_start_atr: 1.0
  trail_atr_mult: 1.0

reentry:
  max_per_day: 2
  cooldown_bars: 3

# ---- Options specific (used only when mode=options) ----
options:
  iv_hint: 0.22              # constant IV fallback for intraday calc
  rate: 0.06                 # annualized risk-free (Black–Scholes)
  expiry: "weekly"           # hint for strike selection logic

# ---- Output ----
out_dir: "reports"

# ---- Telegram (overridden by env in Actions) ----
telegram_bot_token: ""
telegram_chat_id: ""
