# === GLOBAL (common) ===
capital_rs: 100000
order_qty: 1

# === INTRADAY OPTIONS (STRATEGY PARAMS) ===
intraday_options:
  timeframe: "5minute"

  # ENTRY (ORB + VWAP)
  entry:
    orb_first_minutes: 15         # ORB window (e.g., 09:15–09:30 IST)
    use_vwap_filter: true         # enable VWAP context filter
    vwap_side: "with_trend"       # "with_trend" or "both"

  # EXITS (SL/Target/Trailing)
  exits:
    sl_atr_mult: 1.0              # stop distance = ATR * mult
    tgt_rr: 1.5                   # target = entry ± (RR * stop_distance)
    trail_start_rr: 1.0           # start trailing after ≥ 1R in profit
    trail_atr_mult: 1.0           # trail distance = ATR * mult

  # RE-ENTRY (same day)
  reentry:
    max_per_day: 3
    cooldown_bars: 2

  # DAY GUARDRAILS
  guardrails:
    max_trades_per_day: 10        # hard cap on trades/day
    max_daily_loss_rs: 3000       # stop new entries after this loss
    stop_after_target_rs: 5000    # optionally stop after daily target hit

# === BACKTEST BLOCK (same rules as intraday) ===
backtest:
  timeframe: "5minute"
  entry:
    orb_first_minutes: 15
    use_vwap_filter: true
    vwap_side: "with_trend"
  exits:
    sl_atr_mult: 1.0
    tgt_rr: 1.5
    trail_start_rr: 1.0
    trail_atr_mult: 1.0
  reentry:
    max_per_day: 3
    cooldown_bars: 2
  guardrails:
    max_trades_per_day: 10
    max_daily_loss_rs: 3000
    stop_after_target_rs: 5000
