# =========================
# Quant Bot — Base Config
# =========================

# ---- Data / timeframe ----
symbol: "NIFTYBEES.NS"
interval: "1d"
lookback: "5d"             # just fetch a few days, enough to cover yesterday
tz: "Asia/Kolkata"

# ---- Zerodha switch ----
zerodha_enabled: true
zerodha_instrument_token: 256265

# ---- Strategy params ----
ema_fast: 21
ema_slow: 50
rsi_len: 14
rsi_buy: 30
rsi_sell: 70
adx_len: 14
atr_len: 14

# ---- Risk / sizing ----
stop_atr_mult: 2.0
take_atr_mult: 3.0
capital_rs: 100000
order_qty: 1

# ---- Modes ----
send_only_signals: true
paper_trading: true
live_trading: false

# ---- Output ----
out_dir: "reports"

# ---- Simulation control ----
# This ensures the runner cuts off and evaluates ONLY yesterday (India time).
simulate_yesterday_only: true
# Optional: instead of yesterday, you can hard-set a date.
# paper_trade_cutoff: "2025-08-22"   # YYYY-MM-DD

# ---- Telegram (set in GitHub Secrets) ----
telegram_bot_token: ""
telegram_chat_id: ""

# ---- Zerodha creds (set in GitHub Secrets) ----
zerodha_api_key: ""
zerodha_api_secret: ""
zerodha_access_token: ""
