tz: "Asia/Kolkata"
out_dir: "reports"

# --- Secrets (GH Actions માં Secrets વડે ભરાશે) ---
zerodha_enabled: true
ZERODHA_API_KEY: ""
ZERODHA_API_SECRET: ""
ZERODHA_ACCESS_TOKEN: ""
TELEGRAM_BOT_TOKEN: ""
TELEGRAM_CHAT_ID: ""

# --- Capital / sizing ---
capital_rs: 100000
order_qty: 1

# ---------- Global strategy knobs ----------
ema_fast: 21
ema_slow: 50
rsi_len: 14
rsi_buy: 52
rsi_sell: 48
atr_len: 14
ema_poke_pct: 0.0001

# Exits (global mirrors)
stop_atr_mult: 1.0
take_atr_mult: 1.3
trailing_enabled: true
trail_start_atr: 0.5
trail_atr_mult: 1.0

# Re-entries (global)
reentry_max: 12
reentry_cooldown: 0

# ---------- Intraday options (index source) ----------
intraday_options:
  underlying: "BANKNIFTY"
  index_token: 260105
  timeframe: "5minute"
  strike_step: 100
  # legacy compat (unused by new engine but kept safe)
  ma_len: 20
  atr_len: 14
  sl_atr_mult: 1.0
  tgt_rr: 1.3
  trail_start_atr: 0.5
  trail_atr_mult: 1.0
  reentry_max: 12
  reentry_cooldown: 0

send_only_signals: true
paper_trading: true
live_trading: false

# =========================
# Backtest PROFILES
# =========================

# -------- Loose (બહુ ઝારા ટ્રેડ્સ; idea generation) --------
backtest_loose:
  session_start: "09:18"
  session_end:   "15:25"
  slippage_bps: 2.0
  brokerage_flat: 20.0
  brokerage_pct: 0.0003

  ema_fast: 21
  ema_slow: 50
  rsi_len: 14
  rsi_buy: 52
  rsi_sell: 48
  atr_len: 14
  ema_poke_pct: 0.0001

  filters:
    adx_len: 14
    adx_min: 8            # loosest
    use_htf: false
    htf_rule: "15min"
    htf_ema_len: 20
    min_atr_pct: 0.00015  # allow low-vol
    session_start: "09:18"
    session_end:   "15:25"

  reentry:
    max_per_day: 40
    cooldown_bars: 0

  guardrails:
    max_trades_per_day: 40
    max_daily_loss_rs: 3000
    stop_after_target_rs: 5000

  exits:
    stop_atr_mult: 1.0
    take_atr_mult: 1.3
    trail: { type: "atr", atr_mult: 1.0, step_bars: 3 }

# -------- Medium (default; balanced) --------
backtest_medium:
  session_start: "09:20"
  session_end:   "15:20"
  slippage_bps: 2.0
  brokerage_flat: 20.0
  brokerage_pct: 0.0003

  ema_fast: 21
  ema_slow: 50
  rsi_len: 14
  rsi_buy: 52
  rsi_sell: 48
  atr_len: 14
  ema_poke_pct: 0.0001

  filters:
    adx_len: 14
    adx_min: 12          # moderate
    use_htf: false
    htf_rule: "15min"
    htf_ema_len: 20
    min_atr_pct: 0.0002
    session_start: "09:20"
    session_end:   "15:20"

  reentry:
    max_per_day: 30
    cooldown_bars: 0

  guardrails:
    max_trades_per_day: 30
    max_daily_loss_rs: 2500
    stop_after_target_rs: 4000

  exits:
    stop_atr_mult: 1.0
    take_atr_mult: 1.3
    trail: { type: "atr", atr_mult: 1.0, step_bars: 3 }

# -------- Strict (quality-first; ઓછી entries) --------
backtest_strict:
  session_start: "09:25"
  session_end:   "15:15"
  slippage_bps: 2.0
  brokerage_flat: 20.0
  brokerage_pct: 0.0003

  ema_fast: 21
  ema_slow: 50
  rsi_len: 14
  rsi_buy: 53
  rsi_sell: 47
  atr_len: 14
  ema_poke_pct: 0.00012

  filters:
    adx_len: 14
    adx_min: 18          # strict
    use_htf: true        # HTF confirmation ON
    htf_rule: "15min"
    htf_ema_len: 20
    min_atr_pct: 0.00035
    session_start: "09:25"
    session_end:   "15:15"

  reentry:
    max_per_day: 15
    cooldown_bars: 1

  guardrails:
    max_trades_per_day: 15
    max_daily_loss_rs: 2000
    stop_after_target_rs: 3500

  exits:
    stop_atr_mult: 1.0
    take_atr_mult: 1.3
    trail: { type: "atr", atr_mult: 1.0, step_bars: 3 }
