# =========================
# Global / Common
# =========================
tz: "Asia/Kolkata"
out_dir: "reports"

# Zerodha / Telegram (unchanged placeholders)
zerodha_enabled: true
ZERODHA_API_KEY: ""
ZERODHA_API_SECRET: ""
ZERODHA_ACCESS_TOKEN: ""
TELEGRAM_BOT_TOKEN: ""
TELEGRAM_CHAT_ID: ""

# ---- Capital & sizing ----
capital_rs: 100000
order_qty: 1

# =========================
# Intraday Options Algo — GLOBAL knobs (prepare_signals likely reads these)
# =========================
signal_mode: "balanced"

# Entries (loosen a bit)
ema_fast: 21
ema_slow: 50
rsi_len: 14
rsi_buy: 53          # (old 55 / 52 → a bit easier)
rsi_sell: 47
ema_poke_pct: 0.0005

# ADX
adx_len: 14
adx_min_bal: 10
adx_min_strict: 18

# Risk/targets (global)
stop_atr_mult: 1.0   # (old 1.2)
take_atr_mult: 1.8

# Trailing (global)
trailing_enabled: true
trail_start_atr: 0.6
trail_atr_mult: 1.0

# Re-entries (global) — **loosened**
reentry_max: 6       # (old 3)
reentry_cooldown: 1  # (old 2)

# ---- Intraday Options block (index-level sourcing) ----
intraday_options:
  underlying: "BANKNIFTY"
  index_token: 260105
  timeframe: "5minute"
  strike_step: 100

  # legacy mirror (safe)
  ma_len: 20
  atr_len: 14
  sl_atr_mult: 1.0
  tgt_rr: 1.8
  trail_start_atr: 0.6
  trail_atr_mult: 1.0
  reentry_max: 6
  reentry_cooldown: 1

# ---- Modes ----
send_only_signals: true
paper_trading: true
live_trading: false

# =========================
# Backtest block (engine may read from here) — mirror values
# =========================
backtest:
  session_start: "09:20"
  session_end:   "15:20"

  # Execution frictions
  slippage_bps: 2.0
  brokerage_flat: 20.0
  brokerage_pct: 0.0003

  # Strategy params (mirror)
  ema_fast: 21
  ema_slow: 50
  rsi_len: 14
  rsi_buy: 53
  rsi_sell: 47

  reentry:
    max_per_day: 6
    cooldown_bars: 1

  guardrails:
    max_trades_per_day: 20   # (old 6) allow higher frequency
    max_daily_loss_rs: 1800
    stop_after_target_rs: 2500

  exits:
    stop_atr_mult: 1.0
    take_atr_mult: 1.8
    trail:
      type: "atr"
      atr_mult: 1.0
      step_bars: 3
