name: kite-diag

on:
  workflow_dispatch:

jobs:
  diag:
    runs-on: ubuntu-latest

    env:
      ZERODHA_API_KEY:      ${{ secrets.ZERODHA_API_KEY }}
      ZERODHA_API_SECRET:   ${{ secrets.ZERODHA_API_SECRET }}
      ZERODHA_ACCESS_TOKEN: ${{ secrets.ZERODHA_ACCESS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show secrets lengths (safe)
        run: |
          echo "API_KEY len:      ${#ZERODHA_API_KEY}"
          echo "API_SECRET len:   ${#ZERODHA_API_SECRET}"
          echo "ACCESS_TOKEN len: ${#ZERODHA_ACCESS_TOKEN}"

      - name: Install kiteconnect
        run: |
          python -m pip install --upgrade pip
          pip install kiteconnect

      - name: Preflight: call Kite profile()
        run: |
          python - <<'PY'
          import os
          from kiteconnect import KiteConnect

          api = (os.getenv("ZERODHA_API_KEY") or "").strip()
          tok = (os.getenv("ZERODHA_ACCESS_TOKEN") or "").strip()

          print("API len:", len(api), "| TOKEN len:", len(tok))
          if not api or not tok:
              raise SystemExit("❌ Missing API key or Access token in env")

          kite = KiteConnect(api_key=api)
          kite.set_access_token(tok)

          try:
              prof = kite.profile()
              print("✅ OK:", prof.get("user_id"), prof.get("user_name"))
          except Exception as e:
              print("❌ profile() failed:", e)
              raise
          PY
